<?php

namespace Database\Seeders;

use App\Models\Departemen;
use App\Models\Position;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $it = Departemen::query()->where('name', 'Information Technology')->first();
        $hr = Departemen::query()->where('name', 'Human Resource')->first();
        $finance = Departemen::query()->where('name', 'Finance')->first();
        $marketing = Departemen::query()->where('name', 'Marketing')->first();

        $positions = [
            'backend'   => Position::query()->where('name', 'Backend Developer')->first(),
            'frontend'  => Position::query()->where('name', 'Frontend Developer')->first(),
            'fullstack' => Position::query()->where('name', 'Full Stack Developer')->first(),
            'hrstaff'   => Position::query()->where('name', 'HR Staff')->first(),
            'hrmanager' => Position::query()->where('name', 'HR Manager')->first(),
            'finance'   => Position::query()->where('name', 'Finance Staff')->first(),
            'marketing' => Position::query()->where('name', 'Marketing Staff')->first(),
        ];

        $users = [
            // Admin
            [
                'employee_code' => 'ADM001',
                'departement_id' => $it->id,
                'position_id' => $positions['fullstack']->id,
                'name' => 'Administrator',
                'username' => 'admin',
                'email' => 'admin@example.com',
                'role' => 'admin',
                'phone' => '081234567890',
                'hire_date' => '2024-01-15',
                'status' => 'active',
            ],

            // HR
            [
                'employee_code' => 'HR001',
                'departement_id' => $hr->id,
                'position_id' => $positions['hrmanager']->id,
                'name' => 'Rina Wati',
                'username' => 'hr.manager',
                'email' => 'rina.hr@example.com',
                'role' => 'hr',
                'phone' => '081234567891',
                'hire_date' => '2024-02-01',
                'status' => 'active',
            ],
            [
                'employee_code' => 'HR002',
                'departement_id' => $hr->id,
                'position_id' => $positions['hrstaff']->id,
                'name' => 'Dewi Lestari',
                'username' => 'hr.staff1',
                'email' => 'dewi.hr@example.com',
                'role' => 'hr',
                'phone' => '081234567892',
                'hire_date' => '2024-06-10',
                'status' => 'active',
            ],

            // IT - 8 employees
            [
                'employee_code' => 'IT001',
                'departement_id' => $it->id,
                'position_id' => $positions['fullstack']->id,
                'name' => 'Ahmad Rizky',
                'username' => 'ahmad.rizky',
                'email' => 'ahmad@example.com',
                'role' => 'employee',
                'phone' => '081234567893',
                'hire_date' => '2024-03-20',
                'status' => 'active',
            ],
            [
                'employee_code' => 'IT002',
                'departement_id' => $it->id,
                'position_id' => $positions['backend']->id,
                'name' => 'Budi Prasetyo',
                'username' => 'budi.prasetyo',
                'email' => 'budi@example.com',
                'role' => 'employee',
                'phone' => '081234567894',
                'hire_date' => '2024-04-05',
                'status' => 'active',
            ],
            [
                'employee_code' => 'IT003',
                'departement_id' => $it->id,
                'position_id' => $positions['frontend']->id,
                'name' => 'Citra Dewi',
                'username' => 'citra.dewi',
                'email' => 'citra@example.com',
                'role' => 'employee',
                'phone' => '081234567895',
                'hire_date' => '2024-05-12',
                'status' => 'active',
            ],
            [
                'employee_code' => 'IT004',
                'departement_id' => $it->id,
                'position_id' => $positions['backend']->id,
                'name' => 'Dian Permata',
                'username' => 'dian.permata',
                'email' => 'dian@example.com',
                'role' => 'employee',
                'phone' => '081234567896',
                'hire_date' => '2024-06-18',
                'status' => 'active',
            ],
            [
                'employee_code' => 'IT005',
                'departement_id' => $it->id,
                'position_id' => $positions['fullstack']->id,
                'name' => 'Eko Nugroho',
                'username' => 'eko.nugroho',
                'email' => 'eko@example.com',
                'role' => 'employee',
                'phone' => '081234567897',
                'hire_date' => '2024-07-22',
                'status' => 'active',
            ],
            [
                'employee_code' => 'IT006',
                'departement_id' => $it->id,
                'position_id' => $positions['frontend']->id,
                'name' => 'Fitri Handayani',
                'username' => 'fitri.handayani',
                'email' => 'fitri@example.com',
                'role' => 'employee',
                'phone' => '081234567898',
                'hire_date' => '2024-08-01',
                'status' => 'active',
            ],
            [
                'employee_code' => 'IT007',
                'departement_id' => $it->id,
                'position_id' => $positions['backend']->id,
                'name' => 'Gilang Ramadhan',
                'username' => 'gilang.r',
                'email' => 'gilang@example.com',
                'role' => 'employee',
                'phone' => '081234567899',
                'hire_date' => '2024-09-15',
                'status' => 'inactive',
            ],
            [
                'employee_code' => 'IT008',
                'departement_id' => $it->id,
                'position_id' => $positions['fullstack']->id,
                'name' => 'Hana Putri',
                'username' => 'hana.putri',
                'email' => 'hana@example.com',
                'role' => 'employee',
                'phone' => '081234567900',
                'hire_date' => '2025-01-10',
                'status' => 'active',
            ],

            // HR - 5 employees
            [
                'employee_code' => 'HR003',
                'departement_id' => $hr->id,
                'position_id' => $positions['hrstaff']->id,
                'name' => 'Indah Sari',
                'username' => 'indah.sari',
                'email' => 'indah@example.com',
                'role' => 'hr',
                'phone' => '081234567901',
                'hire_date' => '2024-03-10',
                'status' => 'active',
            ],
            [
                'employee_code' => 'HR004',
                'departement_id' => $hr->id,
                'position_id' => $positions['hrstaff']->id,
                'name' => 'Joko Susilo',
                'username' => 'joko.susilo',
                'email' => 'joko@example.com',
                'role' => 'hr',
                'phone' => '081234567902',
                'hire_date' => '2024-05-20',
                'status' => 'active',
            ],
            [
                'employee_code' => 'HR005',
                'departement_id' => $hr->id,
                'position_id' => $positions['hrstaff']->id,
                'name' => 'Kartika Sari',
                'username' => 'kartika.sari',
                'email' => 'kartika@example.com',
                'role' => 'hr',
                'phone' => '081234567903',
                'hire_date' => '2024-08-12',
                'status' => 'active',
            ],
            [
                'employee_code' => 'HR006',
                'departement_id' => $hr->id,
                'position_id' => $positions['hrstaff']->id,
                'name' => 'Lukman Hakim',
                'username' => 'lukman.hakim',
                'email' => 'lukman@example.com',
                'role' => 'hr',
                'phone' => '081234567904',
                'hire_date' => '2024-11-05',
                'status' => 'active',
            ],
            [
                'employee_code' => 'HR007',
                'departement_id' => $hr->id,
                'position_id' => $positions['hrstaff']->id,
                'name' => 'Maya Anggraeni',
                'username' => 'maya.anggraeni',
                'email' => 'maya@example.com',
                'role' => 'hr',
                'phone' => '081234567905',
                'hire_date' => '2025-02-18',
                'status' => 'active',
            ],

            // Finance - 8 employees
            [
                'employee_code' => 'FIN001',
                'departement_id' => $finance->id,
                'position_id' => $positions['finance']->id,
                'name' => 'Nurul Hidayah',
                'username' => 'nurul.hidayah',
                'email' => 'nurul@example.com',
                'role' => 'employee',
                'phone' => '081234567906',
                'hire_date' => '2024-02-14',
                'status' => 'active',
            ],
            [
                'employee_code' => 'FIN002',
                'departement_id' => $finance->id,
                'position_id' => $positions['finance']->id,
                'name' => 'Omar Fauzi',
                'username' => 'omar.fauzi',
                'email' => 'omar@example.com',
                'role' => 'employee',
                'phone' => '081234567907',
                'hire_date' => '2024-03-28',
                'status' => 'active',
            ],
            [
                'employee_code' => 'FIN003',
                'departement_id' => $finance->id,
                'position_id' => $positions['finance']->id,
                'name' => 'Putri Wulandari',
                'username' => 'putri.wulandari',
                'email' => 'putri@example.com',
                'role' => 'employee',
                'phone' => '081234567908',
                'hire_date' => '2024-05-06',
                'status' => 'active',
            ],
            [
                'employee_code' => 'FIN004',
                'departement_id' => $finance->id,
                'position_id' => $positions['finance']->id,
                'name' => 'Rizal Fadillah',
                'username' => 'rizal.fadillah',
                'email' => 'rizal@example.com',
                'role' => 'employee',
                'phone' => '081234567909',
                'hire_date' => '2024-06-20',
                'status' => 'active',
            ],
            [
                'employee_code' => 'FIN005',
                'departement_id' => $finance->id,
                'position_id' => $positions['finance']->id,
                'name' => 'Siti Nurjanah',
                'username' => 'siti.nurjanah',
                'email' => 'siti.n@example.com',
                'role' => 'employee',
                'phone' => '081234567910',
                'hire_date' => '2024-08-08',
                'status' => 'active',
            ],
            [
                'employee_code' => 'FIN006',
                'departement_id' => $finance->id,
                'position_id' => $positions['finance']->id,
                'name' => 'Taufik Rahman',
                'username' => 'taufik.rahman',
                'email' => 'taufik@example.com',
                'role' => 'employee',
                'phone' => '081234567911',
                'hire_date' => '2024-10-15',
                'status' => 'active',
            ],
            [
                'employee_code' => 'FIN007',
                'departement_id' => $finance->id,
                'position_id' => $positions['finance']->id,
                'name' => 'Ulya Maghfiroh',
                'username' => 'ulya.maghfiroh',
                'email' => 'ulya@example.com',
                'role' => 'employee',
                'phone' => '081234567912',
                'hire_date' => '2025-01-20',
                'status' => 'active',
            ],
            [
                'employee_code' => 'FIN008',
                'departement_id' => $finance->id,
                'position_id' => $positions['finance']->id,
                'name' => 'Vina Oktaviani',
                'username' => 'vina.oktaviani',
                'email' => 'vina@example.com',
                'role' => 'employee',
                'phone' => '081234567913',
                'hire_date' => '2025-03-01',
                'status' => 'inactive',
            ],

            // Marketing - 6 employees
            [
                'employee_code' => 'MKT001',
                'departement_id' => $marketing->id,
                'position_id' => $positions['marketing']->id,
                'name' => 'Wahyu Setiawan',
                'username' => 'wahyu.setiawan',
                'email' => 'wahyu@example.com',
                'role' => 'employee',
                'phone' => '081234567914',
                'hire_date' => '2024-02-25',
                'status' => 'active',
            ],
            [
                'employee_code' => 'MKT002',
                'departement_id' => $marketing->id,
                'position_id' => $positions['marketing']->id,
                'name' => 'Xenia Agatha',
                'username' => 'xenia.agatha',
                'email' => 'xenia@example.com',
                'role' => 'employee',
                'phone' => '081234567915',
                'hire_date' => '2024-04-12',
                'status' => 'active',
            ],
            [
                'employee_code' => 'MKT003',
                'departement_id' => $marketing->id,
                'position_id' => $positions['marketing']->id,
                'name' => 'Yusuf Maulana',
                'username' => 'yusuf.maulana',
                'email' => 'yusuf@example.com',
                'role' => 'employee',
                'phone' => '081234567916',
                'hire_date' => '2024-06-30',
                'status' => 'active',
            ],
            [
                'employee_code' => 'MKT004',
                'departement_id' => $marketing->id,
                'position_id' => $positions['marketing']->id,
                'name' => 'Zahra Amelia',
                'username' => 'zahra.amelia',
                'email' => 'zahra@example.com',
                'role' => 'employee',
                'phone' => '081234567917',
                'hire_date' => '2024-09-10',
                'status' => 'active',
            ],
            [
                'employee_code' => 'MKT005',
                'departement_id' => $marketing->id,
                'position_id' => $positions['marketing']->id,
                'name' => 'Andi Saputra',
                'username' => 'andi.saputra',
                'email' => 'andi@example.com',
                'role' => 'employee',
                'phone' => '081234567918',
                'hire_date' => '2024-12-05',
                'status' => 'active',
            ],
            [
                'employee_code' => 'MKT006',
                'departement_id' => $marketing->id,
                'position_id' => $positions['marketing']->id,
                'name' => 'Bella Citra',
                'username' => 'bella.citra',
                'email' => 'bella@example.com',
                'role' => 'employee',
                'phone' => '081234567919',
                'hire_date' => '2025-04-15',
                'status' => 'active',
            ],
        ];

        foreach ($users as $user) {
            User::updateOrCreate(
                ['username' => $user['username']],
                array_merge($user, ['password' => Hash::make('password')])
            );
        }
    }
}
